"""estado inicial

Revision ID: 57c4a551a50d
Revises: 
Create Date: 2026-02-16 11:14:45.814746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57c4a551a50d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.alter_column('banners', 'banner_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'promo'::character varying"))
    op.alter_column('banners', 'order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('banners', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('banners', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('banners', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_banners_id'), 'banners', ['id'], unique=False)
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'cart_items', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    # Crear enums antes de usarlos
    orderstatus = sa.Enum('PENDING', 'PAYMENT_PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus')
    orderstatus.create(op.get_bind(), checkfirst=True)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=15),
               type_=orderstatus,
               existing_nullable=False,
               postgresql_using='status::orderstatus')
    op.alter_column('orders', 'subtotal',
               existing_type=sa.TEXT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False,
               postgresql_using='subtotal::numeric(12,2)')
    op.alter_column('orders', 'shipping_cost',
               existing_type=sa.TEXT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False,
               postgresql_using='shipping_cost::numeric(12,2)')
    op.alter_column('orders', 'total',
               existing_type=sa.TEXT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False,
               postgresql_using='total::numeric(12,2)')
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.add_column('product_images', sa.Column('public_id', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_products_active_category', 'products', ['is_active', 'category_id'], unique=False)
    op.create_index('ix_products_active_created', 'products', ['is_active', 'created_at'], unique=False)
    op.create_index('ix_products_active_featured', 'products', ['is_active', 'is_featured'], unique=False)
    op.create_index('ix_products_active_price', 'products', ['is_active', 'price'], unique=False)
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.create_index(op.f('ix_quote_items_id'), 'quote_items', ['id'], unique=False)
    op.create_foreign_key(None, 'quote_items', 'quotes', ['quote_id'], ['id'], ondelete='CASCADE')
    op.alter_column('quotes', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    quotestatus = sa.Enum('PENDING', 'CONTACTED', 'QUOTED', 'CLOSED', name='quotestatus')
    quotestatus.create(op.get_bind(), checkfirst=True)
    op.alter_column('quotes', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=quotestatus,
               existing_nullable=False,
               postgresql_using='status::quotestatus')
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    op.create_foreign_key(None, 'quotes', 'users', ['user_id'], ['id'])
    userrole = sa.Enum('USER', 'ADMIN', name='userrole')
    userrole.create(op.get_bind(), checkfirst=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=5),
               type_=userrole,
               existing_nullable=False,
               postgresql_using='role::userrole')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted with explicit constraint names ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('USER', 'ADMIN', name='userrole'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.drop_constraint('quotes_user_id_fkey', 'quotes', type_='foreignkey')
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.alter_column('quotes', 'status',
               existing_type=sa.Enum('PENDING', 'CONTACTED', 'QUOTED', 'CLOSED', name='quotestatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('quotes', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint('quote_items_quote_id_fkey', 'quote_items', type_='foreignkey')
    op.drop_index(op.f('ix_quote_items_id'), table_name='quote_items')
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_index('ix_products_active_price', table_name='products')
    op.drop_index('ix_products_active_featured', table_name='products')
    op.drop_index('ix_products_active_created', table_name='products')
    op.drop_index('ix_products_active_category', table_name='products')
    op.drop_constraint('product_images_product_id_fkey', 'product_images', type_='foreignkey')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_column('product_images', 'public_id')
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.alter_column('orders', 'total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('orders', 'shipping_cost',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('orders', 'subtotal',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('PENDING', 'PAYMENT_PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_constraint('cart_items_product_id_fkey', 'cart_items', type_='foreignkey')
    op.drop_constraint('cart_items_user_id_fkey', 'cart_items', type_='foreignkey')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_index(op.f('ix_banners_id'), table_name='banners')
    op.alter_column('banners', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('banners', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('banners', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('banners', 'order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('banners', 'banner_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'promo'::character varying"))
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('whatsapp_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('enable_prices', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enable_purchases', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('business_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('business_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('business_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('business_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('settings_pkey'))
    )
    # ### end Alembic commands ###
